### ISSUE TITLE
UnityServer Stereo Rendering support for HoloLens

### ISSUE THREAD

**Issue by tylergibson** [CatalystCode/3dtoolkit#103]
The UnityServer sample currently doesn't support mode switching into Stereo rendering mode for HoloLens.  It is also not usable because neither the Unity Server nor the Unity HoloLens client have the ability to auto-connect and neither have interactive modes for choosing a peer to connect to.

Using the pattern from Multithreaded Server, implement the same mode switching to stereo rendering on HoloLens.

**Comment by bengreenier** [comment]
grabbing this work, as @phongcao and i discussed it's a priority, but i'll only be able to pick it up after my last bit of auth stuff lands (hoping for today, 9/26/17 📆 )

**Comment by bengreenier** [comment]
> Note: we're tracking this work on `feature/unity-server-stereo` branch, feel free to follow along.

So far we've got:

+ Unity server sample using unity's built in XR stack to do stereo rendering
+ Unity server ui to connect to clients
+ WebRTCUWP M58 upgrade (required dependency)
+ Unity client connecting

And are dealing with a bug where video drops out (or crawls to a halt) ~5s in with local testing. Next update when we've solved that bug.

**Comment by bengreenier** [comment]
We also need to think through and implement mono <=> stereo switching, but the architecture for this new stereo stuff is pretty flexible so I'm hoping it'll be fairly trivial to circle back to switching once we have both mono and stereo samples working.

**Comment by phongcao** [comment]
Really good progress, we're getting there!

**Comment by bengreenier** [comment]
with regard to the video drop outs, this turned out to not be a bug, but just what occurs while bitrate is stabilizing, and is worsened on bad connections. @anderm recommends the following `nvEncode.json` settings to make this experience better:

```
{
  "useSoftwareEncoding": false,
  "serverFrameCaptureFPS": 30,
  "NvencodeSettings": {
    "bitrate": 5500000,
    "minBitrate": 0,
    "fps": 30,
    "qp": 5,
    "intraRefreshPeriod": 60,
    "intraRefreshEnableFlag": false,
    "intraRefreshDuration": 6,
    "enableTemporalAQ": false,
    "invalidateRefFramesEnableFlag": true,
    "nvEncodeProfile": 2,
    "nvEncodeProfile_comment": "nvEncodeProfile enums: 1 - NV_ENC_H264_PROFILE_MAIN_GUID; 2 - NV_ENC_PRESET_LOW_LATENCY_HQ_GUID; 3 - NV_ENC_H264_PROFILE_STEREO_GUID; 0 - NV_ENC_CODEC_PROFILE_AUTOSELECT_GUID"
  }
}
```

**Comment by bengreenier** [comment]
I am testing out a unity frame limiter on the server side to run the entire unity experience at a lower framerate..ideally this should be sync-ed with the framerate in the encoder config, so I may parse that here. I want to first understand if this impacts encoding at all (if we tick unity @ 60fps but have config @ 30fps does it sample properly). Either way though we should probably sync these two for perf (no reason to eat more cycles than we need for rendering).

**Comment by bengreenier** [comment]
looking and moving now works (as of https://github.com/CatalystCode/3dtoolkit/commit/fdc8cb5e4baf04096c1cfb672e60557ed2ff34db) so you can now look around and move around the cube.

need to circle back and investigate framerate, then switching modes, then we can PR this work

**Comment by bengreenier** [comment]
mono => stereo works as of 3a0934f6cab7b9284694f96bbfcfad08721edbe2

**Comment by bengreenier** [comment]
we need to surface `PeerConnectionObserver` hooks to unity so that we can write application code that is aware of when streams are added/removed. This will enable us to do things like hide the menu when a client initiates connection.
