### ISSUE TITLE
WebRTCUWP clients cannot create/establish connections

### ISSUE THREAD

**Issue by bengreenier** [CatalystCode/3dtoolkit#105]
UnityClient and HololensUWP are both unable to be the establishing party (the one sending the sdp `offer` message) - this is likely an issue with h264 codec negotiation, and can be fixed with something like [this webclient workaround](https://github.com/CatalystCode/3dtoolkit/blob/master/Samples/Client/WebClient/index.html#L134).

This was surfaced by trying to add autoconnect behavior to the unity client by calling `ConnectToPeer()` from within the `OnPeerConnected` event.

We verified this issue is present in the UWP hololens client as well, which leads us to believe the issue is related to WebRTCUWP.

**Comment by anderm** [comment]
Resolved with #129
