### ISSUE TITLE
UnityServer closing crash

### ISSUE THREAD

**Issue by bengreenier** [CatalystCode/3dtoolkit#109]
`Unity-FractalStream` server sample crashes on close. This is apparently known, on `master`, and has been present for some time.

**Comment by bengreenier** [comment]
So far, i've learned that on `master` this isn't a "crash", it's an infinite hang. when you don't connect at all, it seems to be caused by `s_conductor` being `null`, and `s_closing` never getting set to `true` - which causes the main loop to never terminate. that ones an easy..looking at other cases before attempting a fix.

**Comment by anderm** [comment]
Resolved with #129
