### ISSUE TITLE
hololens exception behind proxy

### ISSUE THREAD

**Issue by bengreenier** [CatalystCode/3dtoolkit#111]
On certain networks, the hololens can fail to connect to the service for signalling, but may still receive a `200` status. This will cause [this code](https://github.com/CatalystCode/3dtoolkit/blob/master/Plugins/UnityClientPlugin/WebRtcWrapper/Signalling/Signalling.cs#L172) to fail and throw an exception. We should try and detect these situations better, but we may be unable to do so (ie: transparent proxy).

For example, our guest network proxy appliance uses the following trick:
```
<html>
<head>
<meta http-equiv='refresh' content='1; url=http://<signaling_server_address>/sign_in?peer_name=hololens-qfrtq&arubalp=59beda57-187d-4d56-ad05-928b617a58'>
</head>
</html>
```

Which breaks us.

**Comment by bengreenier** [comment]
this is tagged documentation because we should probably document proxy.

**Comment by bengreenier** [comment]
we found out this was because we weren't authenticated on our proxy client and it was stonewalling us. since this is for a transparent proxy and we can't detect, @phongcao and I agreed we'll close this out for now.

**Comment by phongcao** [comment]
Sorry about the false alarm. Thanks a lot for helping, Ben!

**Comment by bengreenier** [comment]
to clarify, this can occur if you're connected to a "guest" style wifi network, that requires browser interaction to authenticate. 

If you connect to the network, and then try to run our code (without first logging in) you'll see weird http responses that are effectively the proxy preventing the traffic from going out, and instead sending a redirect to their login page. __The fix is to open a browser after connecting to the network and before running our app, and first login.__
