### ISSUE TITLE
UnityHoloClient fails to parse webRtc config file when ran on PC

### ISSUE THREAD

**Issue by korzen** [CatalystCode/3dtoolkit#113]
Hi,

the Holo Unity client has problems finding or parsing the webRTC config file on PC.
It happens when I am building the Unity client project for PC
and running it as PC app. Nevertheless, it should work fine, right? 

Here are the exceptions:

Exception thrown: 'System.UriFormatException' in System.Private.Uri.dll
Exception thrown: 'System.UriFormatException' in mscorlib.ni.dll

The path is:
_configFilePath = "ms-appx:///Data/StreamingAssets/webrtcConfig.json"

and this fails (line 270, WebRtcControl.cs)
`            StorageFile configFile = await StorageFile.GetFileFromApplicationUriAsync(
                new Uri(_configFilePath))
                .AsTask()
                .ConfigureAwait(false);`

Thanks for checking this out

**Comment by korzen** [comment]
Hi Ben,

thanks for a quick reply. I understand, I am new to UWP and I just thought that any UWP app should work without problems on a PC as well. Anyways, I was just testing your software on a PC as I don't have access to HoloLens at the moment. 

Keep up the good work!

Best wishes

Kay

**Comment by phongcao** [comment]
Hi @korzen,

You're right about UWP app. However, our app renders stereo video stream and requires the HoloLens input to update the camera for left/right eyes. If you want to try it on your PC, you can just download the HoloLens emulator:

https://developer.microsoft.com/en-us/windows/mixed-reality/install_the_tools

Cheers,
Phong

**Comment by bengreenier** [comment]
i'm going to close this issue out as i believe it's resolved 💯
