### ISSUE TITLE
Very bad image quality and latency on HoloLens in local network

### ISSUE THREAD

**Issue by korzen** [CatalystCode/3dtoolkit#132]
Hi, 

I am XR developer at Virtual Engineering Lab at Volkswagen AG.

I have just fetched the latest sources and the build finished smoothly, without any problems.

I am starting the signaling server, spinning cube server (release) and a dx holo client (also release).
In the config files I turn on the software encoding on the server and set   iceConfiguration to none on both client and server. 

I am getting very pixelized image and around 3s of latency when walking around. This is also the case for Unity client.

I tried the remoting from Unity and it works super smooth so my LAN and WiFi are unlikely to cause this problem.

Is it possible that the actual communication goes via some external server?
If yes, how can this be fixed?
If no, any other idea?

Thank you

Przemyslaw Korzeniowski

**Comment by phongcao** [comment]
Hi Przemyslaw Korzeniowski,

Can you use hardware encoder on the server since it provides higher quality image with less latency? Also try setting the fps to 30 since currently HoloLens can't afford 60fps.

Just try and let me know.

**Comment by korzen** [comment]
Hi Phong Cao,

thanks for a quick response. After your suggestions the spinning server is still not usable. However, I have noticed that the multithreaded one got much better. The quality and latency still can't match the one from Unity remoting but it is kind of usable now.

Tomorrow I will try again the fractal server. Last time, I couldn't connect Hololens native client to it. Normally, on cube or squid servers when hololens connects to signalling it is getting listed there and I click simply to start the streaming on both. However on Unity Fractal Server there is no such a "lobby". Any way around it? 

Thanks

**Comment by phongcao** [comment]
We're working on improving the performance on HoloLens so will keep you posted.
Regarding the FractalStream server, it fully works now so you can follow the document here:
https://github.com/CatalystCode/3dtoolkit/wiki/Unity-Fractal-Server

**Comment by phongcao** [comment]
Hi @korzen, would you want to give it a try on our new branch having some performance improvement for HoloLens? Currently, it only works with the DirectX samples but we've planned on working for Unity next.

**Comment by korzen** [comment]
Thanks Phong Cao, I haven't got access to HoloLens at the moment but will try at the earliest possible opportunity.

**Comment by korzen** [comment]
Hi @phongcao,

I have tried to build the current  image-stabilisation branch (Release x86 and x64) but I get the following errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'set_prediction_timestamp': is not a member of 'webrtc::VideoFrame'	StreamingNativeServerPlugin	E:\_MEDAPP\CatalystCode\3dtoolkit\Plugins\NativeServerPlugin\src\custom_video_capturer.cpp	258	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'set_staging_frame_buffer': is not a member of 'webrtc::VideoFrame'	StreamingNativeServerPlugin	E:\_MEDAPP\CatalystCode\3dtoolkit\Plugins\NativeServerPlugin\src\custom_video_capturer.cpp	255	

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		constexpr function return is non-constant	StreamingNativeServerPlugin	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXMath.h	268	

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1501	No overload for method 'CreateMediaStreamSource' takes 4 arguments	StreamingDirectxHololensClient	E:\CatalystCode\3dtoolkit\Samples\Client\DirectxUWP\DirectxClient\App.cs	72	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		static assertion failed with ".data() and .size() are private"	StreamingNativeServerPlugin	e:\CatalystCode\3dtoolkit\Libraries\WebRTC\headers\webrtc\base\type_traits.h	70

**Comment by korzen** [comment]
Again, for clarity:

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		constexpr function return is non-constant	StreamingNativeServerPlugin	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXMath.h	268	

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		constexpr function return is non-constant	StreamingNativeServerPlugin	c:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\DirectXMath.h	269	

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1501	No overload for method 'CreateMediaStreamSource' takes 4 arguments	StreamingDirectxHololensClient	E:\_MEDAPP\CatalystCode\3dtoolkit\Samples\Client\DirectxUWP\DirectxClient\App.cs	72	Active

**Comment by phongcao** [comment]
Hi Przemyslaw Korzeniowski, look like you're still using the old libraries. Can you try doing a fresh clone and re-run **setup.cmd**?

**Comment by korzen** [comment]
Hi, I did and the WebRTC was updated via setup.cmb but not DxTK. 

Anyways, I made a fresh clone, setup.cmd and it builds fine now on x86 Release, which is enough to try out the performance tomorrow. Thanks

**Comment by bengreenier** [comment]
@korzen @phongcao looks like the underlying issue is likely resolved here, using our new libraries should get perf to it's best possible state. As such, closing!

@korzen If you still see perf worst than expected, feel free to reopen! 😸
