### ISSUE TITLE
Azure N-Series Support

### ISSUE THREAD

**Issue by morsh** [CatalystCode/3dtoolkit#141]
Add prerequisites and support for scallable deployment support for Azure N-Series machines (Windows/Linux)

**Comment by tylergibson** [comment]
We do have n-series support via the Visual studio deployment projects here: https://github.com/CatalystCode/3dtoolkit/tree/master/Samples/Server/Directx-SpinningCube/Deploy 

And after discussing in person, I think we merged this offline with the fixes in #142 and #145.  Thanks for the help!
