### ISSUE TITLE
HoloLens image stabilization - Remaining issues

### ISSUE THREAD

**Issue by phongcao** [CatalystCode/3dtoolkit#148]
Basing on @anderm's feedback, these are the remaining works:

- Update information about the custom WebRTC UWP repo that works with prediction time stamp.
- Write unit tests for the [BufferCapturer](https://github.com/CatalystCode/3dtoolkit/blob/master/Plugins/NativeServerPlugin/src/buffer_capturer.cpp) class.
- Add documentation about how the image stabilization and prediction time stamp work.

**Comment by anderm** [comment]
Closing as individual issues were created:
#181 #180 #179
