### ISSUE TITLE
Troubles with setting up unity client for hololens

### ISSUE THREAD

**Issue by machur** [CatalystCode/3dtoolkit#162]
Guys, I'm having troubles with running unity client on hololens. 

I've followed steps from https://github.com/CatalystCode/3dtoolkit/wiki/Unity-Hololens-Client to set it up and used simple signaling server from https://github.com/anastasiia-zolochevska/signaling-server. I already tested signaling server by setting up multithreaded server and desktop client - connection had been established properly, applications were "talking", it all worked flawlessly.

I haven't changed frame sizes and use default 1280x720 for multithreaded server, 2560x720 for unity client. In both config files iceConfiguration has been set to "none", default turn server has been used. The last status update I see on hololens is "signed in" and "connected peer". I checked out the flow and it looks as follows:
- server connects to signaling server and starts sending regular frames,
- hololens client connects to signaling server and sends message that enables stereo rendering,
- server seems to process that message properly and respons with stream of stereo frames.

At that moment UI of my server application freezes and becomes unresponsive. There is also no new data/hologram visible on hololens. Am I missing something? Is there any further configuration needed?

**Comment by phongcao** [comment]
Hi @machur, is the StreamingDirectxClientHololens working for you?

**Comment by machur** [comment]
@phongcao StreamingDirectxClientHololens doesn't work for me either. Server application froze just after being paired with hololens client.

**Comment by phongcao** [comment]
@machur Recently we've just added some new features so it may break the HoloLens clients. In order to help us debug more, could you please try the following and let me know:

1. Use the MultithreadedServer sample app, set the resolution to **1280x720** in _serverConfig.json_.
2. Use StreamingDirectxClientHololens, set the **VIDEO_FRAME_WIDTH** to **2560** and **VIDEO_FRAME_HEIGHT** to **720** in _App.cs_.
3. Run both in Release mode and provide the logs from the HoloLens client.

Thanks,
Phong

**Comment by machur** [comment]
Just tested both directx and unity client in different network and they worked fine, it looks like there was an issue with network capacity. Still the server apps become unresponsive when the streaming starts and sometimes the hologram disappears from hololens view. Attaching logs from directx client (several exceptions were thrown, maybe you'll find them useful anyway):

Video rotation changed: 0
Video frame size changed for media W=2560 H=720
The thread 0xdf8 has exited with code 0 (0x0).
The thread 0x1e0 has exited with code 0 (0x0).
The thread 0xfa8 has exited with code 0 (0x0).
The thread 0xcec has exited with code 0 (0x0).
The thread 0x2a0 has exited with code 0 (0x0).
The thread 0xdd0 has exited with code 0 (0x0).
The thread 0x3d8 has exited with code 0 (0x0).
CORRECTION_SAMPLE_DURATION!!!
The thread 0xcf8 has exited with code 0 (0x0).
The thread 0xc10 has exited with code 0 (0x0).
CORRECTION_SAMPLE_DURATION!!!
CORRECTION_SAMPLE_DURATION!!!
CORRECTION_SAMPLE_DURATION!!!
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.Threading.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Net.Http.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Net.Http.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
The thread 0x640 has exited with code 0 (0x0).
CORRECTION_SAMPLE_DURATION!!!
CORRECTION_SAMPLE_DURATION!!!
'StreamingDirectxHololensClient.exe' (Win32): Unloaded 'C:\Windows\System32\Windows.Shell.ServiceHostBuilder.dll'
'StreamingDirectxHololensClient.exe' (Win32): Unloaded 'C:\Windows\System32\mlang.dll'
'StreamingDirectxHololensClient.exe' (Win32): Unloaded 'C:\Windows\System32\deviceaccess.dll'
'StreamingDirectxHololensClient.exe' (Win32): Unloaded 'C:\Windows\System32\Windows.ApplicationModel.dll'
CORRECTION_SAMPLE_DURATION!!!
The thread 0x458 has exited with code 0 (0x0).
CORRECTION_SAMPLE_DURATION!!!
CORRECTION_SAMPLE_DURATION!!!
The thread 0x740 has exited with code 0 (0x0).
CORRECTION_SAMPLE_DURATION!!!
The thread 0xe4c has exited with code 0 (0x0).
CORRECTION_SAMPLE_DURATION!!!
The thread 0x410 has exited with code 0 (0x0).
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.Threading.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Net.Http.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Net.Http.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
The thread 0x63c has exited with code 0 (0x0).
CORRECTION_SAMPLE_DURATION!!!

**Comment by phongcao** [comment]
@machur `The Exception thrown: 'System.Threading.Tasks.TaskCanceledException'` makes the hologram disappear after running for a few minutes. This is a known issue and the workaround is setting the debugging type to 'Native Only' or just run without debugging attached. I'm closing this issue now but feel free to create a new one if you don't agree.
