### ISSUE TITLE
Support for Safari Browser clients (JS Lib + WebClient Sample)

### ISSUE THREAD

**Issue by zaxy78** [CatalystCode/3dtoolkit#164]
Hi !

I'm using the `3dtoolkit` and noticed it's not compatible with **Safari** browser, 
although Safari supports WebRTC since June 2017. 

I've made it work on my side, mostly though fixes in [`adapter.js`](https://github.com/webrtc/adapter) (PR PR) library.
Would it be a problem for you guys to include `adapter.js` intto `3dtoolkit`?
At least in the Web Client Sample, but also potentially in the JS 3dtoolkit Lib itself. 

It helps a lot with browsers differences, and might have saved you guys few tens of lines of code.
It is possible ofcouse to add the Safari APIs to the "adaptation lines of code" you guys used in the repo, manually.

I can suggest some pull request with the fixes, and allow the repo to enjoy support for Safari clients.

My only question is - would you take the easy path of including `adapter.js` , or would you insist in making the changes manually inside the lib?

**Comment by bengreenier** [comment]
@zaxy78 closing this here in favor of the referenced issue in the js library repo! 👍
