### ISSUE TITLE
Latency measurements for hololens client

### ISSUE THREAD

**Issue by machur** [CatalystCode/3dtoolkit#165]
Hi, we need to test different network configurations in order to determine which one would work best for our use case. I see that you run several efficiency tests with hololens on your own (issue #133). Did you use any tool for measuring latency/capacity that you would recommend? If not, are there any hooks in the code for tracking such data?

**Comment by phongcao** [comment]
@machur We've recently added that feature in the DirectX client. You can enable **SHOW_DEBUG_INFO** flag:

https://github.com/CatalystCode/3dtoolkit/blob/master/Samples/Client/DirectxUWP/DirectxClientComponent/Content/VideoRenderer.h#L6

**Comment by machur** [comment]
@phongcao thanks!
