### ISSUE TITLE
Create client and server 

### ISSUE THREAD

**Issue by parandham03** [CatalystCode/3dtoolkit#170]
Hi,
I need to build Unity Fractal Server application to hololens and Unity client to pc standalone . Also run signaling server in a local pc. Is it possible to achieve this. Kindly help me to do this.

**Comment by phongcao** [comment]
@parandham03, I think that what you need to use is WebRTC-UWP with MRC enabled. You can check it here:
https://github.com/ortclib/ortclib-sdk/tree/Mosa/20180320-peercc-unity
