### ISSUE TITLE
Peer list is not cleared in the multi-user scenario

### ISSUE THREAD

**Issue by anderm** [CatalystCode/3dtoolkit#174]
Connecting multiple servers and clients to the multi-peer scenario (https://github.com/CatalystCode/3dtoolkit/wiki/Multi-peer) causes the peer list to be flooded with names. These are not being properly released when the client/server disconnects. 

Repro steps: 
Run a multi-peer signaling server [webrtc-signal-http-capacity](https://github.com/bengreenier/webrtc-signal-http-capacity) 
Connect multiple clients and servers and close the connection. 
The clients/servers that disconnected are not removed from the peer list

**Comment by bengreenier** [comment]
Hey @anderm - we'll want to use as the correct new signaling implementation: https://github.com/bengreenier/3dtoolkit-signal closing this out as that should resolve this.
