### ISSUE TITLE
Authentication configuration

### ISSUE THREAD

**Issue by machur** [CatalystCode/3dtoolkit#177]
Hi, I'm struggling to setup and test a simple authentication. So far I've been using sample signaling server from https://github.com/anastasiia-zolochevska/signaling-server. I switched to the versions from https://github.com/anastasiia-zolochevska/signaling-server-http-auth and https://github.com/anastasiia-zolochevska/3dtoolkit-identity-management with proper support (although the latter fails to start with authentication disabled). I have an active Azure AAD that might be used to generate endpoints and ids.

The configuration seems quite complex and lacking documentation (or rather consisting of multiple confusing descriptions under different issues as I dug a little deeper). Would you please provide me with more details on how to set up authentication for server/client? Also what signaling server would you recommend to use?

**Comment by phongcao** [comment]
cc @bengreenier

**Comment by bengreenier** [comment]
Hi @machur, The configuration is definitely not super well documented today. our core team is making a push to better document and test much of our work here over the next month. That said, here's a start:

![image](https://user-images.githubusercontent.com/1167891/39771759-48355a84-52c1-11e8-98fd-dd0198aac0ed.png)


We're consolidating all of our different signaling server implementations into [this project](https://github.com/bengreenier/3dtoolkit-signal) and are currently considering it a beta release. If you'd be willing to test and give feedback on the cutting edge stuff, that would be super valuable. I'll describe the steps below for the signaling implementations you call out above, and note the differences in this new one.

## Prework:

1) [Create an AAD Tenant](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-howto-tenant)
2) [Create an AAD B2C Application](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-app-registration) (used for client login)
3) [Create a Normal AAD Application](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal) (used for server login)
4) Record tenant name and app id's for use below
5) (optional) setup [TURN](https://en.wikipedia.org/wiki/Traversal_Using_Relays_around_NAT) if you need to support advanced NAT traversal scenarios. We have an article about how we did this [here](https://www.microsoft.com/developerblog/2018/01/29/orchestrating-turn-servers-cloud-deployment).
6) (optional) record TURN postgres credential information

## Setup Signaling Authentication:

> This secures transmission of [sdp](https://webrtchacks.com/sdp-anatomy/) messages, which are the session establishment messages. It's how our clients find servers, and vice versa.

1) deploy [signaling](https://github.com/anastasiia-zolochevska/signaling-server-http-auth) to azure. This is greatly simplified in the beta (just click the deploy button), but to learn more please see [this walkthrough](https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-nodejs). 
2) in [App Settings](https://docs.microsoft.com/en-us/azure/app-service/web-sites-configure) set the following (note: for [beta](https://github.com/bengreenier/3dtoolkit-signal) these are defined in [the readme](https://github.com/bengreenier/3dtoolkit-signal/blob/master/README.md)):
    + `AAD_TENANT_ID` your aad tenant info. ex: `3dtoolkit.onmicrosoft.com`
    + `AAD_B2C_CLIENT_APPLICATION_ID` your add client app id. ex: `aacf1b7a-104c-4efe-9ca7-9f4916d6b66a`
     + `AAD_B2C_POLICY_NAME` your aad b2c policy name. ex: `b2c_1_signup` 
     + `AAD_RENDERING_SERVER_APPLICATION_ID` your aad server app id. ex: `5b4df04b-e3bb-4710-92ca-e875d38171b3`

## Setup Identity Management:

> This secures [TURN](https://en.wikipedia.org/wiki/Traversal_Using_Relays_around_NAT) such that short lived temporary credentials are used, and further ensures that only AAD authenticated users can retrieve said credentials. __If you aren't using TURN in production, you don't need this__.

1) deploy [identity management](https://github.com/anastasiia-zolochevska/3dtoolkit-identity-management) to azure. This is still needed even in the beta.
2) in [App Settings](https://docs.microsoft.com/en-us/azure/app-service/web-sites-configure) set the following:
    + `PGUSER` your TURN postgres username
    + `PGDATABASE` your TURN postgres database name
    + `PGPASSWORD` your TURN postgres password
    + `PGHOST` your TURN postgres hostname/fqdn
    + `PGPORT` your TURN postgres port
    + `AAD_TENANT_ID` your aad tenant info
    + `AAD_B2C_CLIENT_APPLICATION_ID` your add client app id
    + `AAD_B2C_POLICY_NAME` your aad b2c policy name
    + `AAD_RENDERING_SERVER_APPLICATION_ID` your aad server app id
    + `AAD_B2C_CLIENT_APPLICATION_SECRET` your aad client app secret
    + `AAD_B2C_REDIRECT_URI` your aad client app redirect uri (should be identity management service site with a specific path. ex: `<siteName>.azurewebsites.net/device/login`)

## Setup OAuth24D:

> This hands out credentials to clients, using short-lived device tokens and a user device to login. We have an article about how we did this, and why it exists [here](https://www.microsoft.com/developerblog/2018/04/23/oauth-2-0-mixed-reality-applications/).

1) modify [app.js](https://github.com/bengreenier/oauth24d/blob/master/examples/server/node/app.js) to use a real [passportjs](http://www.passportjs.org/) strategy, likely [passport-azure-ad](https://github.com/azuread/passport-azure-ad) (__no public example yet, see https://github.com/bengreenier/oauth24d/issues/2__).
2) deploy the modified [oauth24d](https://github.com/bengreenier/oauth24d/tree/master/examples/server/node) to azure. This is still needed even in the beta.
3) in [App Settings]() set the following:
    + `AUTH_URI` the user facing authentication url (should be oauth24d service site with a specific path. ex: `<siteName>.azurewebsites.net/login`)
    + Optional settings exist, please see [the readme](https://github.com/bengreenier/oauth24d/blob/master/examples/server/node/README.md) for more info

## Configuration:

> See [webrtcConfig](https://github.com/CatalystCode/3dtoolkit/wiki/JSON-Config-Files#webrtc-configuration-webrtcconfigjson) for more info

For the client, we need to point it to the oauth24d service. This requires two urls in the `authentication` config section in `webrtcConfig.json`:

```
"authentication": {
    "codeUri": "<siteName>.azurewebsites.net/new",
    "pollUri": "<siteName>.azurewebsites.net/poll"
}
```

This tells the client to use the oauth24d authentication flow to direct a user to a uri to login, and give the application a token it can use to authenticate to the other services.

For the server, we need to point it to azure ad. This requires a few values in the `authentication` config section in `webrtcConfig.json`:

```
"authentication": {
    "authority": "<an oauth2 authority uri, tested against aadv1>",
    "resource": "<the oauth2 resource, commonly the same as clientId>",
    "clientId": "<the oauth2 authority application id>",
    "clientSecret": "<the oauth2 authority application secret>"
}
```

These are the same values as observed in setup above, with one caveat - authority maps to https://login.microsoftonline.com/`AAD_TENANT_ID`.onmicrosoft.com/oauth2/token. For instance, `https://login.microsoftonline.com/3dtoolkit.onmicrosoft.com/oauth2/token`. This tells the server to use client_credentials aad grant to get a token it can use to authenticate to other services.

## Realtime data:

Realtime data channel messaging is encrypted using DTLS [by default](https://github.com/CatalystCode/3dtoolkit/blob/master/Plugins/NativeServerPlugin/src/peer_conductor.cpp#L195). Please note that if you're using TURN, data will be decrypted on the TURN node, while it is handed off to the other peer (effectively exposing [MITM](https://en.wikipedia.org/wiki/Man-in-the-middle_attack) potential on that node). Realtime video channel communications are encrypted using SRTP [by default](https://github.com/CatalystCode/3dtoolkit/blob/master/Plugins/NativeServerPlugin/src/peer_conductor.cpp#L195). You can learn more [here](http://webrtc-security.github.io/#4.3.).

**Comment by bengreenier** [comment]
I captured this info into [the wiki](https://github.com/CatalystCode/3dtoolkit/wiki/Configuring-authentication) as well. As such, i'm going to close this one out for now. ✔️ 

@machur please let me know if this isn't detailed enough or you find any issues, would be happy to clarify/improve this and re-open the issue if needed! 🚀
