### ISSUE TITLE
Merge native and UWP WebRTC libraries into one

### ISSUE THREAD

**Issue by anderm** [CatalystCode/3dtoolkit#194]
We need to merge all 3dtoolkit patches into one unified library. This includes:
- [x] Unified Video Frame extensions for frame prediction
- [x] Merge UWP MF encoder and NvPipe encoder
- [x] Unify MediaEngine decoding implementations
- [x] Update documentation

**Comment by anderm** [comment]
MediaEngine implementation does not work correctly on Desktop UWP. More work is required on the MediaStreamSource implementation to add correct timestamps and duration. Since UWP Desktop client is out of scope at the moment, we will use the MediaEngine only for HoloLens clients.

**Comment by machur** [comment]
@anderm I would like to make sure we're on the same page - it's out of scope of that task, but MediaEngine will still be adapted, so both HL and Desktop clients may be implemented in UWP architecture?

**Comment by anderm** [comment]
@machur MediaEngine will be available on UWP clients but initial tests show that the feed is not stable on desktop. As soon as this task is finished, we will add new issues to track MediaEngine performance on UWP desktop.

**Comment by anderm** [comment]
closed with #240

**Comment by machur** [comment]
Guys, I see that you merged WebRTC dependencies, so transition to UWP architecture should be possible now. Does it also mean that current native server plugin is fully compatible with UWP? Are you planning to work on any further tasks regarding UWP implementation in the toolkit?
