### ISSUE TITLE
Decide on testing platform for 3dtoolkit

### ISSUE THREAD

**Issue by anderm** [CatalystCode/3dtoolkit#196]

**Comment by bengreenier** [comment]
We need to understand if this license is acceptable for Microsoft OSS projects: https://github.com/google/googletest/blob/master/LICENSE

**Comment by bengreenier** [comment]
semi-related, we want `setup.ps1` to be run as part of the build

**Comment by bengreenier** [comment]
we'll close this after we've landed on the licensing issue. then we'll open another issue to track the project migration to the new stuff, and migrating existing tests
