### ISSUE TITLE
Spaces in directory names cause build to fail

### ISSUE THREAD

**Issue by KanishkT123** [CatalystCode/3dtoolkit#199]
Tested on Debug and Release versions of x64. Having a space anywhere in the directory structure causes the entire build to fail, as the xcopy commands stop functioning as expected.

**Comment by KanishkT123** [comment]
The simple workaround is to rename the directory to not have spaces in it. This is not always possible, so I've changed the xcopy commands so that all directories are in quotes: "$(DIR)" . This allows for spaces to be used in the filenames without a problem. Should be fixed in #197 once the PR goes through.

**Comment by bengreenier** [comment]
fixed in #197
