### ISSUE TITLE
VSTS build agent is broken with VS 2017 x64 

### ISSUE THREAD

**Issue by anderm** [CatalystCode/3dtoolkit#228]
## Report

- [x] I have searched [existing issues](https://github.com/CatalystCode/3dtoolkit/issues) and this is not a duplicate.

## Environment

- OS Version: Windows Server 2012 R2

- SDK Version: 10.0.14393.0

- Visual Studio Version: 2017

## Issues and Steps to Reproduce
Attempt a VSTS 3dtoolkit build targeted at Visual Studio 2017. 

## Expected Behavior
Build should run successfully and all tests pass. 

## Actual Behavior
Build fails when building solution with x64 configuration. Samples\Client\DirectxUWP\DirectxClient\StreamingDirectxHololensClient.csproj fails to successfully restore nuget packages. 

## Link to Code
This might be related to: https://developercommunity.visualstudio.com/content/problem/30858/visualstudio2017-cannot-develop-uwp-on-windows-ser.html 

The build definition can be found here: https://dpeted.visualstudio.com/TED%20Strategic%20Engagements%20(Agile)/_build/index?definitionId=189&_a=completed

**Comment by bengreenier** [comment]
Review green vs17 build: https://dpeted.visualstudio.com/TED%20Strategic%20Engagements%20(Agile)/_build/index?buildId=16383&_a=summary

Review build def: https://dpeted.visualstudio.com/TED%20Strategic%20Engagements%20(Agile)/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=189

**Comment by anderm** [comment]
Everything is green ✔️ Let's switch to this CI build

**Comment by bengreenier** [comment]
@anderm made the switch 🚀
