### ISSUE TITLE
Refactor JSON config into isolated library

### ISSUE THREAD

**Issue by tylergibson** [CatalystCode/3dtoolkit#56]
Currently we are read/writing to JSON configuration files from different places with a lot of duplicated code.  We should refactor into a single lib to handle loading, creation and updating from JSON.

1) If json config isn't present, create file with defaults
2) Defaults stored in single location per config
3) Bad/missing elements gracefully default & provide log info

Primarily for nvencconfig & webrtcconfig - should we also abstract data channel payload schemas to json?

**Comment by bengreenier** [comment]
we also should not parse `webrtcConfig.json` file twice anymore (once in [main](https://github.com/CatalystCode/3dtoolkit/blob/master/Samples/Client/DirectxWin32/src/main.cpp#L106) and once in [conductor](https://github.com/CatalystCode/3dtoolkit/blob/master/Samples/Client/DirectxWin32/src/conductor.cpp#L151))
