### ISSUE TITLE
DirectX Client video locks up over SSL

### ISSUE THREAD

**Issue by tylergibson** [CatalystCode/3dtoolkit#67]
With the feature/native-auth and in the master branch, the client video stream stops functioning after 10-15 seconds and never returns.  This occurs over TURN and STUN, and also occurs when connecting the client to older server instances.  It is somewhat random, sometimes it will run for minutes, but once the video stream locks up, disconnect and reconnecting will resume video but only for a short period of time

This also happens over both http and https, with and without auth.

**Comment by phongcao** [comment]
This happens because recently we increase the min bitrate to **3500000**. We should reset it to 0 and fix the flickering issue instead.
