### ISSUE TITLE
azure sdk is a dependency for deployment projects

### ISSUE THREAD

**Issue by bengreenier** [CatalystCode/3dtoolkit#68]
Right now, if you open the `.sln` without having the azure sdk installed, you see a warning about deployment projects ([DirectX-Multithread](https://github.com/CatalystCode/3dtoolkit/blob/master/Samples/Server/Directx-Multithreaded/MultithreadedServerService.vcxproj) for example) not being able to load.

How should we communicate or deal with this?

**Comment by bengreenier** [comment]
![image](https://user-images.githubusercontent.com/1167891/29674243-9697276a-88bf-11e7-9d51-081154c9d7a8.png)

**Comment by tylergibson** [comment]
Fixed by adding dependency on AzureSDK to readme documentation prerequisites 
https://github.com/CatalystCode/3dtoolkit/commit/7e33031673beef7919a84f49a937561bba49fda9
