### ISSUE TITLE
Can't build StreamingDirectXHololensClient

### ISSUE THREAD

**Issue by leo92613** [CatalystCode/3dtoolkit#69]
The error we see is 

```
3>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\IlcInternals.targets(318,5): error : Error: Windows Runtime metadata is invalid in Windows SDK, follow the steps in http://go.microsoft.com/fwlink/?LinkId=733341 to repair your installation.
```

<details>
<summary>See the full build log</summary>

Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1>------ Rebuild All started: Project: WebRtcWrapper, Configuration: Release x86 ------
2>------ Rebuild All started: Project: DirectxClientComponent, Configuration: Release Win32 ------
2>  compilation object save succeeded; see C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Build\x86\Release\DirectxClient\GeometryShader.cso
2>  compilation object save succeeded; see C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Build\x86\Release\DirectxClient\PixelShader.cso
2>  compilation object save succeeded; see C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Build\x86\Release\DirectxClient\VertexShader.cso
2>  compilation object save succeeded; see C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Build\x86\Release\DirectxClient\VPRTVertexShader.cso
2>  MediaEngine.cpp
2>  MediaEnginePlayer.cpp
2>  MediaHelpers.cpp
2>  CameraResources.cpp
2>  DeviceResources.cpp
2>  VideoRenderer.cpp
2>  HolographicAppMain.cpp
2>  AppCallbacks.cpp
1>C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Plugins\UnityClientPlugin\WebRtcWrapper\WebRtcControl.cs(30,55,30,80): warning CS0067: The event 'WebRtcControl.OnPeerDataChannelReceived' is never used
1>C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Plugins\UnityClientPlugin\WebRtcWrapper\WebRtcControl.cs(39,37,39,48): warning CS0649: Field 'WebRtcControl._ntpService' is never assigned to, and will always have its default value null
1>C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Plugins\UnityClientPlugin\WebRtcWrapper\WebRtcControl.cs(37,33,37,48): warning CS0414: The field 'WebRtcControl._peerVideoTrack' is assigned but its value is never used
1>  WebRtcWrapper -> C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Build\x86\Release\WebRtcWrapper\WebRtcWrapper.dll
1>  Target Plugin Path is C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Plugins\UnityClientPlugin\WebRtcWrapper\..\..\..\Samples\Client\Unity\Assets\
1>  A subdirectory or file C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Plugins\UnityClientPlugin\WebRtcWrapper\..\..\..\Samples\Client\Unity\Assets\Plugins already exists.
1>  A subdirectory or file C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Plugins\UnityClientPlugin\WebRtcWrapper\..\..\..\Samples\Client\Unity\Assets\Plugins\WSA already exists.
1>  A subdirectory or file C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Plugins\UnityClientPlugin\WebRtcWrapper\..\..\..\Samples\Client\Unity\Assets\Plugins\WSA\x86 already exists.
1>  C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Build\x86\Release\WebRtcWrapper\WebRtcWrapper.dll
1>  1 File(s) copied
1>  C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Build\x86\Release\WebRtcWrapper\WebRtcWrapper.pdb
1>  1 File(s) copied
1>  C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Build\x86\Release\WebRtcWrapper\Org.WebRtc.dll
1>  1 File(s) copied
1>  C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Build\x86\Release\WebRtcWrapper\Org.WebRtc.winmd
1>  1 File(s) copied
2>..\..\..\..\Plugins\UnityClientPlugin\MediaEngineUWP\Shared\MediaEnginePlayer.cpp(306): warning C4244: '=': conversion from 'float' to 'LONG', possible loss of data
2>..\..\..\..\Plugins\UnityClientPlugin\MediaEngineUWP\Shared\MediaEnginePlayer.cpp(307): warning C4244: '=': conversion from 'float' to 'LONG', possible loss of data
2>..\..\..\..\Plugins\UnityClientPlugin\MediaEngineUWP\Shared\MediaEnginePlayer.cpp(477): warning C4244: 'argument': conversion from 'UINT32' to 'float', possible loss of data
2>..\..\..\..\Plugins\UnityClientPlugin\MediaEngineUWP\Shared\MediaEnginePlayer.cpp(492): warning C4244: 'argument': conversion from 'UINT32' to 'float', possible loss of data
2>..\..\..\..\Plugins\UnityClientPlugin\MediaEngineUWP\Shared\MediaEnginePlayer.cpp(775): warning C4244: '=': conversion from 'float' to 'LONG', possible loss of data
2>..\..\..\..\Plugins\UnityClientPlugin\MediaEngineUWP\Shared\MediaEnginePlayer.cpp(776): warning C4244: '=': conversion from 'float' to 'LONG', possible loss of data
2>..\..\..\..\Plugins\UnityClientPlugin\MediaEngineUWP\Shared\MediaEnginePlayer.cpp(777): warning C4244: '=': conversion from 'float' to 'LONG', possible loss of data
2>..\..\..\..\Plugins\UnityClientPlugin\MediaEngineUWP\Shared\MediaEnginePlayer.cpp(778): warning C4244: '=': conversion from 'float' to 'LONG', possible loss of data
2>c:\users\leola\documents\medivis\streamtoolkit\3dtoolkit\samples\client\directxuwp\directxclientcomponent\AppCallbacks.h(25): warning C4453: 'Windows::ApplicationModel::Core::CoreApplicationView': A '[WebHostHidden]' type should not be used on the published surface of a public type that is not '[WebHostHidden]' (compiling source file AppCallbacks.cpp)
2>c:\users\leola\documents\medivis\streamtoolkit\3dtoolkit\samples\client\directxuwp\directxclientcomponent\AppCallbacks.h(27): warning C4453: 'Windows::UI::Core::CoreWindow': A '[WebHostHidden]' type should not be used on the published surface of a public type that is not '[WebHostHidden]' (compiling source file AppCallbacks.cpp)
2>Content\VideoRenderer.cpp(23): warning C4244: 'initializing': conversion from 'float' to 'int', possible loss of data
2>Content\VideoRenderer.cpp(24): warning C4244: 'initializing': conversion from 'float' to 'int', possible loss of data
2>Content\VideoRenderer.cpp(29): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
2>Content\VideoRenderer.cpp(30): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
2>Content\VideoRenderer.cpp(32): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
2>Content\VideoRenderer.cpp(33): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
2>Content\VideoRenderer.cpp(34): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
2>Content\VideoRenderer.cpp(37): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
2>Content\VideoRenderer.cpp(38): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
2>Content\VideoRenderer.cpp(40): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
2>Content\VideoRenderer.cpp(41): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
2>Content\VideoRenderer.cpp(42): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
2>AppCallbacks.cpp(29): warning C4453: 'Windows::ApplicationModel::Core::CoreApplicationView': A '[WebHostHidden]' type should not be used on the published surface of a public type that is not '[WebHostHidden]'
2>AppCallbacks.cpp(35): warning C4453: 'Windows::UI::Core::CoreWindow': A '[WebHostHidden]' type should not be used on the published surface of a public type that is not '[WebHostHidden]'
2>     Creating library C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Build\x86\Release\DirectxClient\DirectxClientComponent.lib and object C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Build\x86\Release\DirectxClient\DirectxClientComponent.exp
2>  Generating code
2>  All 3918 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
2>  Finished generating code
2>  DirectxClientComponent.vcxproj -> C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Build\x86\Release\DirectxClient\DirectxClientComponent.dll
2>  DirectxClientComponent.vcxproj -> C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Build\x86\Release\DirectxClient\DirectxClientComponent.pdb (Full PDB)
2>  C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Build\x86\Release\DirectxClient\GeometryShader.cso
2>  C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Build\x86\Release\DirectxClient\PixelShader.cso
2>  C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Build\x86\Release\DirectxClient\VertexShader.cso
2>  C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Build\x86\Release\DirectxClient\VPRTVertexShader.cso
2>  4 File(s) copied
3>------ Rebuild All started: Project: StreamingDirectxHololensClient, Configuration: Release x86 ------
3>  StreamingDirectxHololensClient -> C:\Users\leola\Documents\Medivis\StreamToolKit\3dtoolkit\Build\x86\Release\DirectxClient\StreamingDirectxHololensClient.exe
3>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1930,5): warning APPX0104: Certificate file 'StreamingDirectxHololensClient_TemporaryKey.pfx' not found.
3>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1930,5): warning APPX0102: A certificate with thumbprint 'A3C0FEEFC5C5EFF2AEE1191F50451266B313CAEE' that is specified in the project cannot be found in the certificate store. Please specify a valid thumbprint in the project file.
3>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1930,5): warning APPX0107: The certificate specified is not valid for signing. For more information about valid certificates, see http://go.microsoft.com/fwlink/?LinkID=241478.
3>  Starting .NET Native compilation
3>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\IlcInternals.targets(318,5): error : Error: Windows Runtime metadata is invalid in Windows SDK, follow the steps in http://go.microsoft.com/fwlink/?LinkId=733341 to repair your installation. 
3>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\IlcIntern

</details>

**Comment by phongcao** [comment]
To resolve this problem, you need to repair the Windows SDK and tools for Windows 10, version 1511.
Steps to repair:
1) Start -> Control Panel
2) Under Programs choose “uninstall a program”.
3) This will present a dialog with all the applications installed on your Windows operating system.   In the upper right hand corner type “kit”.   This will filter the list of installed programs.  One of the filtered applications will be “Windows Software Development Kit – Windows 10.0.10586.15”
4) Single click on Windows Software Development Kit – Windows 10.0.10586.15, and choose “change”.
5) This will present the Windows Software Development Kit setup dialog and there is an option to “repair”.  Select repair and click Next.

This will repair the installation of your Windows SDK and tools for Windows 10, version 1511.

**Comment by bengreenier** [comment]
If you've reached this issue and you __don't have the sdk at all__ you can get it [here](https://developer.microsoft.com/en-us/windows/downloads/sdk-archive) - you need the `10.0.14393.795` version.

These repair steps seem to fix the issue, closing!
