### ISSUE TITLE
Error on long path

### ISSUE THREAD

**Issue by JoshuaChoiSynchro** [CatalystCode/3dtoolkit#70]
This git was cloned into a folder with long names.

When the solution was building, path-related errors occurred.

After re-cloning the repo in root C:, it was GOOD.

**Comment by bengreenier** [comment]
we should use `robocopy` instead of `xcopy` in our post-build steps, which should alleviate this pain

**Comment by bengreenier** [comment]
this is a visual studio limitation (present in 2017, even)

![image](https://user-images.githubusercontent.com/1167891/29942257-3586843a-8e63-11e7-8263-ae49baebd9bd.png)

Closing, as there's no way for us to resolve this currently without migrating our entire toolchain.
