### ISSUE TITLE
incorrect build output directory for unknown sub-project

### ISSUE THREAD

**Issue by bengreenier** [CatalystCode/3dtoolkit#72]
When building, you may see a `Build\Debug` directory, when you should only see the `<architecture>\<configuration>` folder only (like `Build\x86\Debug`)

This needs some investigation to figure out which project is incorrectly creating this folder

**Comment by phongcao** [comment]
Yeah, I noticed this issue long time ago and it's quite confusing. Will try to fix it this week.

**Comment by tylergibson** [comment]
This appears to be fixed with https://github.com/CatalystCode/3dtoolkit/pull/93 which removed invalid UWP configurations.  Will leave open to see if it pops up again, but master no longer repros with any solution or project.

**Comment by tylergibson** [comment]
This has no repro locally or in any CI builds since #93, closing as fixed
