### ISSUE TITLE
README clarification for new users

### ISSUE THREAD

**Issue by ActiveNick** [CatalystCode/3dtoolkit#74]
- Should point out that the prebuilt binaries are only for those "consuming" the project, vs the build process which is for project contributors.
- Should clarify in what rare instances would rebuilding the WebRTC libraries be required. This is a rare occurrence that is already taken care of in the CI builds and most devs won't need this, and therefore will not need the Windows DDK.
- We should be clear that in order to run the setup script, you should have the execution mode set to unrestricted in PowerShell.
- Replace the "Finished" message during Setup in PowerShell to more clearly say "Step 1 of X completed: insertstepname here".
- The comment about "this patch" should be expanded to explain what the patch is and why it exists (since you called attention to it).

**Comment by ashanhol** [comment]
Additionally, the last link in [Installing Prebuilt Libraries for 3DToolkit DirectX](https://github.com/catalystcode/3dtoolkit#installing-prebuilt-libraries-for-3dtoolkit-directx), the words "the solution", redirects to a 404. :)
