### ISSUE TITLE
auto-enable software encoder when nvenc hardware is missing

### ISSUE THREAD

**Issue by phongcao** [CatalystCode/3dtoolkit#78]
Currently if the machine running server app doesn't support nvenc (either it doesn't have the required NVIDIA GPU or the system picks the wrong default graphics card), there is no video render on client although the input still works. In order to fix this, we should either raise the error or set to software encoder automatically if the hardware isn't supported.

**Comment by bengreenier** [comment]
+1 to software encoder automatically 😄 💪

**Comment by bengreenier** [comment]
it's worth noting here that this would mask issues like #83, which (probably) wouldn't be desirable.

**Comment by phongcao** [comment]
Agree, we would need to alert user that the app is forced running in software encoder mode.

**Comment by phongcao** [comment]
Closed thanks to #158.
