### ISSUE TITLE
Client crashes on Windows 10 running on MacBook Pro 2013 via Bootcamp

### ISSUE THREAD

**Issue by ActiveNick** [CatalystCode/3dtoolkit#80]
Client crashes on Windows 10 10493 (Anniversary) running on MacBook Pro 2013 via Bootcamp. Debug dump shows WebRTC throwing the error about the audio device is unsupported in Windows core audio. This is trying to use a Cirrus Logic CS4208 (AB 94) audio adapter.

An issue was filed on WebRTC and a patch was merged in the project but would need to verify we are consuming the fixed branch of WebRTC: https://bugs.chromium.org/p/webrtc/issues/detail?id=7220. 

In the meantime, if you disable the audio device in Windows, the client will work fine.

**Comment by phongcao** [comment]
Thanks @ActiveNick. The temporary workaround for this issue is disabling the audio devices.

**Comment by bengreenier** [comment]
We should better document (probably in the wiki) the macbook workaround before closing this out.

**Comment by bengreenier** [comment]
documented in [the wiki FAQ](https://github.com/CatalystCode/3dtoolkit/wiki/FAQ).

on MacOS you should be able to disable the audio device by right clicking on the device in [the audio midi setup app](https://support.apple.com/en-us/HT202968)

on Windows via bootcamp you should be able to disable the audio device by right clicking the speaker icon in the taskbar, choosing playback devices, right clicking on the device and choosing disable.
