### ISSUE TITLE
unity server sample fails to connect

### ISSUE THREAD

**Issue by leo92613** [CatalystCode/3dtoolkit#82]
I follow the steps build the 3dtoolkit solution and also all the plugin for Unity.

Successfully built the standalone app on Windows, run the app with command line to -force-d3d11-no-singlethreaded but I can't find the server from the Client app

**Comment by phongcao** [comment]
Hi @leo92613, did you edit the info in **webrtcConfig.json** which should be placed in the same folder with the executable?

**Comment by leo92613** [comment]
Hi Phong,

Yes I did, I change to the new signaling server I host on Azure

Best,
Wenbo

**Comment by phongcao** [comment]
Hey Wenbo, did you build the **main_cloud** scene? Only that one has webrtc integrated.

**Comment by leo92613** [comment]
Hi Phong,

I build the main_cloud scene.
Because the fact that I wasn’t able to deploy the TURN server.
I set the config file from relay to none.

Wenbo

**Comment by phongcao** [comment]
In the Build Settings, can you try with **x86_64** instead of x86 architecture? Let me know if you can find the server from client app.

**Comment by leo92613** [comment]
I set to x86_64 and still doesn't work.

I change the config files in both unity project and also after build.

Just to confirm
.\WebRTCServer.exe -force-d3d11-no-singlethreaded
this is the way I should do in command line right?

Best,
Wenbo

**Comment by phongcao** [comment]
Yes, that looks perfect to me. I just tried and it seems to be working from my side. Let me think about what could be the other issues.

**Comment by leo92613** [comment]
Thanks!

I actually found another bug, will report it once I can get my hands on VM.

Best,
Wenbo

**Comment by phongcao** [comment]
@bengreenier The **MultithreadedTestRunner** project seems broken now. It shouldn't have anything related to webrtc (headers + libs). This is what it looks like before:

![capture](https://user-images.githubusercontent.com/9741323/29841482-903fcb3e-8cd3-11e7-9bc9-c47e3f97c622.JPG)

**Comment by phongcao** [comment]
It turns out that Unity 64-bit doesn't like x86 dll so it fails to load _StreamingUnityServerPlugin.dll_. The solution is rebuilding the plugin (StreamingUnityServerPlugin.sln) as **x64** and change the build settings in Unity editor to **x86_64**.
