### ISSUE TITLE
unable to select peer in unity samples

### ISSUE THREAD

**Issue by leo92613** [CatalystCode/3dtoolkit#84]
Just a question,

If I'm building both the client and server in Unity, how can I select connection since neither of them has the interface ( as in Multithreadserver.exe) to do that.

Thanks,
Wenbo

**Comment by phongcao** [comment]
Hi Wenbo, this is a known issue and we're working on improving the UI so that you can choose the connection. Will keep you posted.

**Comment by bengreenier** [comment]
@leo92613 we're also more than happy to take a pr that adds that better ui infrastructure to either of both of those projects 😸

**Comment by bengreenier** [comment]
this is closely related to https://github.com/CatalystCode/3dtoolkit/issues/61

**Comment by anderm** [comment]
UI added for Unity server with #129 but we still need a UI for the Unity client sample

**Comment by anderm** [comment]
Tracked in #61, closing this issue
