### ISSUE TITLE
how does authentication work, and how can we leverage it?

### ISSUE THREAD

**Issue by bengreenier** [CatalystCode/3dtoolkit#88]
when working with the toolkit a common question is "how do we secure access to our services, and ensure our clients are used only by authenticated users".

We need to answer and document this question.

**Comment by bengreenier** [comment]
https://sketchboard.me/pADZoc1BiANH

**Comment by bengreenier** [comment]
Documented oauth24d api design spec here: https://github.com/bengreenier/oauth24d/tree/master

Note: this matches our sample implementation: https://github.com/anastasiia-zolochevska/3dtoolkit-identity-management/pull/1

**Comment by bengreenier** [comment]
Our server authentication (https://github.com/CatalystCode/3dtoolkit/blob/master/Libraries/Authentication/inc/server_authentication_provider.h) is a vanilla aadv1 implementation, as documented by aad [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-oauth-service-to-service)

**Comment by ashanhol** [comment]
Wiki page here: https://github.com/CatalystCode/3dtoolkit/wiki/Configuring-authentication

TODO: Fill out description/walkthrough for client and server

**Comment by bengreenier** [comment]
see #177
