### ISSUE TITLE
Exception thrown: 'System.AggregateException' in mscorlib.ni.dll on Hololens unity build

### ISSUE THREAD

**Issue by leo92613** [CatalystCode/3dtoolkit#96]
I try to build the hololens client following the guide.

Build succeeded but can't run on the hololens.

here is the full output from the Unity Client:

'UnityX86.exe' (CoreCLR: DefaultDomain): Loaded 'c:\data\Programs\WindowsApps\Microsoft.NET.CoreRuntime.1.0_1.0.23819.0_x86__8wekyb3d8bbwe\mscorlib.ni.dll'. Cannot find or open the PDB file.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\entrypoint\UnityX86.exe'. Symbols loaded.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.Runtime.dll'. Cannot find or open the PDB file.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\WinMetadata\Windows.winmd'. Module was built without symbols.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\UnityPlayer.winmd'. Module was built without symbols.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.Runtime.InteropServices.WindowsRuntime.dll'. Cannot find or open the PDB file.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.Runtime.WindowsRuntime.dll'. Cannot find or open the PDB file.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\WinRTBridge.winmd'. Cannot find or open the PDB file.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\BridgeInterface.winmd'. Module was built without symbols.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.Collections.dll'. Cannot find or open the PDB file.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\UnityEngine.dll'. Symbols loaded.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\Assembly-CSharp.dll'. Symbols loaded.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\Org.WebRtc.winmd'. Module was built without symbols.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\UnityEngine.Networking.dll'. Symbols loaded.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\UnityEngine.HoloLens.dll'. Symbols loaded.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\UnityEngine.UI.dll'. Symbols loaded.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\nunit.framework.dll'. Symbols loaded.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.Reflection.dll'. Module was built without symbols.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.Globalization.dll'. Module was built without symbols.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.IO.dll'. Cannot find or open the PDB file.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.Linq.dll'. Cannot find or open the PDB file.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.Net.Primitives.dll'. Cannot find or open the PDB file.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.Private.Networking.dll'. Cannot find or open the PDB file.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\Microsoft.Win32.Primitives.dll'. Cannot find or open the PDB file.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.ObjectModel.dll'. Cannot find or open the PDB file.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\WebRtcWrapper.dll'. Symbols loaded.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.Reflection.Primitives.dll'. Module was built without symbols.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.Runtime.Extensions.dll'. Cannot find or open the PDB file.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.Threading.Tasks.dll'. Cannot find or open the PDB file.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.Xml.XDocument.dll'. Cannot find or open the PDB file.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.Private.Uri.dll'. Cannot find or open the PDB file.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.Xml.ReaderWriter.dll'. Cannot find or open the PDB file.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.Text.Encoding.dll'. Module was built without symbols.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.Text.RegularExpressions.dll'. Cannot find or open the PDB file.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\UnityEngine.VR.dll'. Symbols loaded.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.Runtime.InteropServices.dll'. Cannot find or open the PDB file.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.Threading.dll'. Cannot find or open the PDB file.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.Diagnostics.Debug.dll'. Cannot find or open the PDB file.
Module information:
 Built with Compiler Ver '190023918'
 Built from '5.6/release' branch
 Version is '5.6.0f3 (497a0f351392)'
 Release build
 Application type 'D3D11'
 Used 'UWP'

 OS 'Windows 10 (10.0.14393)'

PlayerConnection initialized from C:/Data/Users/DefaultAccount/AppData/Local/DevelopmentFiles/UnityX86VS.Release_x86.leola/Data (debug = 0)

PlayerConnection initialized network socket : 0.0.0.0 55342

Multi-casting "[IP] 10.0.0.9 [Port] 55342 [Flags] 2 [Guid] 506219090 [EditorId] 4294967295 [Version] 1048832 [Id] MetroPlayerX86(HoloLens-7JN8J) [Debug] 0" to [225.0.0.222:54997]...

Started listening to [0.0.0.0:55342]

Player data archive not found at `C:/Data/Users/DefaultAccount/AppData/Local/DevelopmentFiles/UnityX86VS.Release_x86.leola/Data/data.unity3d`, using local filesystem
GfxDevice: creating device client; threaded=1

Direct3D:

    Version:  Direct3D 11.0 [level 11.1]

    Renderer: HoloLens Graphics (ID=0x22b0)

    Vendor:   Intel

    VRAM:     604 MB

Initialize engine version: 5.6.0f3 (497a0f351392)

'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\UnityEngineProxy.dll'. Cannot find or open the PDB file.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.Reflection.Extensions.dll'. Module was built without symbols.
Logical Screen DPI is 144.00.

If your machine has multiple graphics adapters, Unity may have created a WindowContext on the wrong adapter. If you experience a black screen when playing, please restart the Editor.
 
(Filename: C:/buildslave/unity/build/Runtime/VR/VRDevice.cpp Line: 184)

UnloadTime: 4.841515 ms

'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.Collections.Concurrent.dll'. Cannot find or open the PDB file.
'UnityX86.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Data\Users\DefaultAccount\AppData\Local\DevelopmentFiles\UnityX86VS.Release_x86.leola\System.Threading.Timer.dll'. Module was built without symbols.
Exception thrown: 'System.AggregateException' in mscorlib.ni.dll
Setting up 1 worker threads for Enlighten.

  Thread -> id: 874 -> priority: 1 

The thread 0x1604 has exited with code 0 (0x0).
The thread 0x1044 has exited with code 0 (0x0).
Holographic Tracking State Lost. New State: 4
 
(Filename: C:/buildslave/unity/build/Runtime/VR/HoloLens/HoloLensWorldManager.cpp Line: 130)

Holographic Tracking State Active.
 
(Filename: C:/buildslave/unity/build/Runtime/VR/HoloLens/HoloLensWorldManager.cpp Line: 126)

The program '[1232] UnityX86.exe' has exited with code -1 (0xffffffff).

**Comment by phongcao** [comment]
@leo92613 Can you try again with Unity 5.6.1f1 (64-bit)?

**Comment by leo92613** [comment]
@phongcao 
I tried 5.6.1 and rebuild the plugin
Now the editor reports error when build

Plugin 'Org.WebRtc.winmd' is used from several locations:
 Assets/Plugins/WSA/x86/Org.WebRtc.winmd would be copied to <PluginPath>/Org.WebRtc.winmd
 Assets/Plugins/WSA/x64/Org.WebRtc.winmd would be copied to <PluginPath>/Org.WebRtc.winmd
Please fix plugin settings and try again.

**Comment by tylergibson** [comment]
@leo92613 be sure you only use x86 plugins.  We actually just fixed this in master yesterday.  Delete the /x64/ folder and it should build properly :)

**Comment by leo92613** [comment]
@tylergibson 

After deletion, I can build on the Hololens.
But hololens client is not showing on the server side.

I pulled the repo so I'm using the up-to-date code

**Comment by tylergibson** [comment]
@leo92613 I believe we can close this issue now as it is more accurately covered by #103 and #105
